// Which marker icons are DIRECTIONAL — i.e. their glyph encodes a world
// bearing (arrows, task graphics like SBF/AOA, oriented lines), as opposed
// to "upright" point symbols (flags, dots, TRP, letter badges) that should
// always face the viewer.
//
// The 3D viewport uses this to decide per marker how to treat `rotation`:
//   - directional → rotation is a WORLD bearing; the icon is re-projected to
//     the correct on-screen angle every frame (tracks camera yaw/tilt).
//   - upright     → rotation is a SCREEN rotation, baked once, exactly like
//     the 2D viewport renders it.
//
// Hand-maintained: markerLibrary.ts is generated by scripts/extract-markers.mjs,
// so this set lives here instead of on the IconEntry records. Quads are
// globally unique across both atlases.
export const DIRECTIONAL_QUADS = new Set<string>([
  // TS Better Markers (user-confirmed set, 2026-08-02 — everything else
  // stays screen-upright/"static")
  "ts-bof", // SBF
  "ts-abf",
  "ts-aoa-right",
  "ts-aoa-left",
  "ts-aoa-straight",
]);

export function isDirectionalIcon(icon: { quad: string }): boolean {
  return DIRECTIONAL_QUADS.has(icon.quad);
}
