export type MapConfig = {
  key: string;
  label: string;
  imagePath: string;
  /** World coords at the bottom-left and upper-right of the image. */
  worldBL: [number, number];
  worldUR: [number, number];
  /** Optional raw uint16 heightmap (.bin) + sidecar JSON for elevation readout. */
  heightmapBin?: string;
  heightmapMeta?: string;
  /** If set, render via Leaflet TileLayer with this URL template instead of the single-image
   *  ImageOverlay. Generated by tools/map-gen/tile_pyramid.py. Example:
   *  "/tiles/zimnitrita/{z}/{x}/{y}.jpg". */
  tilePattern?: string;
  /** Max zoom level available in the tile pyramid (inclusive, 0 = whole map in 1 tile). */
  tileMaxZoom?: number;
};

export const MAPS: MapConfig[] = [
  {
    key: "arland",
    label: "Arland",
    imagePath: "/arland_final.jpg",
    worldBL: [0, 0],
    worldUR: [4100, 4100],
    heightmapBin: "/heightmaps/arland.bin",
    heightmapMeta: "/heightmaps/arland.json",
    tilePattern: "/tiles/arland/{z}/{x}/{y}.jpg",
    tileMaxZoom: 5,
  },
  {
    key: "everon",
    label: "Everon",
    imagePath: "/everon_final.jpg",
    worldBL: [0, 0],
    worldUR: [13000, 13000],
    heightmapBin: "/heightmaps/everon.bin",
    heightmapMeta: "/heightmaps/everon.json",
    tilePattern: "/tiles/everon/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "kolguyev",
    label: "Kolguyev",
    imagePath: "/kolguyev_final.jpg",
    worldBL: [0, 0],
    worldUR: [13000, 13000],
    heightmapBin: "/heightmaps/kolguyev.bin",
    heightmapMeta: "/heightmaps/kolguyev.json",
    tilePattern: "/tiles/kolguyev/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "zarichne",
    label: "Zarichne",
    imagePath: "/zarichne_final.jpg",
    worldBL: [0, 0],
    worldUR: [4600, 4600],
    heightmapBin: "/heightmaps/zarichne.bin",
    heightmapMeta: "/heightmaps/zarichne.json",
    tilePattern: "/tiles/zarichne/{z}/{x}/{y}.jpg",
    tileMaxZoom: 5,
  },
  {
    key: "zargabad",
    label: "Zargabad",
    imagePath: "/zargabad_final.jpg",
    worldBL: [0, 0],
    worldUR: [8000, 8000],
    heightmapBin: "/heightmaps/zargabad.bin",
    heightmapMeta: "/heightmaps/zargabad.json",
    tilePattern: "/tiles/zargabad/{z}/{x}/{y}.jpg",
    tileMaxZoom: 5,
  },
  {
    key: "zimnitrita",
    label: "Zimnitrita",
    imagePath: "/zimnitrita_final.jpg",
    worldBL: [0, 0],
    worldUR: [16400, 16400],
    heightmapBin: "/heightmaps/zimnitrita.bin",
    heightmapMeta: "/heightmaps/zimnitrita.json",
    tilePattern: "/tiles/zimnitrita/{z}/{x}/{y}.jpg",
    tileMaxZoom: 7,
  },
  {
    key: "serhiivka",
    label: "Serhiivka",
    imagePath: "/serhiivka_final.jpg",
    worldBL: [0, 0],
    worldUR: [10000, 10000],
    heightmapBin: "/heightmaps/serhiivka.bin",
    heightmapMeta: "/heightmaps/serhiivka.json",
    tilePattern: "/tiles/serhiivka/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "takistan",
    label: "Takistan",
    imagePath: "/takistan_final.jpg",
    worldBL: [0, 0],
    worldUR: [12900, 12900],
    heightmapBin: "/heightmaps/takistan.bin",
    heightmapMeta: "/heightmaps/takistan.json",
    tilePattern: "/tiles/takistan/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "ruha",
    label: "Ruha",
    imagePath: "/ruha_final.jpg",
    worldBL: [0, 0],
    worldUR: [8000, 8000],
    heightmapBin: "/heightmaps/ruha.bin",
    heightmapMeta: "/heightmaps/ruha.json",
    tilePattern: "/tiles/ruha/{z}/{x}/{y}.jpg",
    tileMaxZoom: 5,
  },
  {
    key: "anizay",
    label: "Anizay",
    imagePath: "/anizay_final.jpg",
    worldBL: [0, 0],
    worldUR: [10200, 10200],
    heightmapBin: "/heightmaps/anizay.bin",
    heightmapMeta: "/heightmaps/anizay.json",
    tilePattern: "/tiles/anizay/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "chernarus",
    label: "Chernarus",
    imagePath: "/chernarus_final.jpg",
    worldBL: [0, 0],
    worldUR: [15360, 15360],
    heightmapBin: "/heightmaps/chernarus.bin",
    heightmapMeta: "/heightmaps/chernarus.json",
    tilePattern: "/tiles/chernarus/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "faircroft",
    label: "Faircroft Islands",
    imagePath: "/faircroft_final.jpg",
    worldBL: [0, 0],
    worldUR: [12800, 12800],
    heightmapBin: "/heightmaps/faircroft.bin",
    heightmapMeta: "/heightmaps/faircroft.json",
    tilePattern: "/tiles/faircroft/{z}/{x}/{y}.jpg",
    tileMaxZoom: 6,
  },
  {
    key: "armenhof",
    label: "Armenhof",
    imagePath: "/armenhof_final.jpg",
    worldBL: [0, 0],
    worldUR: [3840, 3840],
    heightmapBin: "/heightmaps/armenhof.bin",
    heightmapMeta: "/heightmaps/armenhof.json",
    tilePattern: "/tiles/armenhof/{z}/{x}/{y}.jpg",
    tileMaxZoom: 4,
  },
  {
    key: "alhadra",
    label: "Al Hadra",
    imagePath: "/alhadra_final.jpg",
    worldBL: [0, 0],
    worldUR: [8192, 8192],
    heightmapBin: "/heightmaps/alhadra.bin",
    heightmapMeta: "/heightmaps/alhadra.json",
    tilePattern: "/tiles/alhadra/{z}/{x}/{y}.jpg",
    tileMaxZoom: 5,
  },
  {
    key: "seitenbuch",
    label: "Seitenbuch",
    imagePath: "/seitenbuch_final.jpg",
    worldBL: [0, 0],
    worldUR: [4000, 2000],
    heightmapBin: "/heightmaps/seitenbuch.bin",
    heightmapMeta: "/heightmaps/seitenbuch.json",
    tilePattern: "/tiles/seitenbuch/{z}/{x}/{y}.jpg",
    tileMaxZoom: 4,
  },
  {
    key: "iraq1990",
    label: "Iraq 1990",
    imagePath: "/iraq1990_final.jpg",
    worldBL: [0, 0],
    worldUR: [4000, 4000],
    heightmapBin: "/heightmaps/iraq1990.bin",
    heightmapMeta: "/heightmaps/iraq1990.json",
    tilePattern: "/tiles/iraq1990/{z}/{x}/{y}.jpg",
    tileMaxZoom: 4,
  },
  {
    key: "kunar",
    label: "Kunar Province",
    imagePath: "/kunar_final.jpg",
    worldBL: [0, 0],
    worldUR: [4000, 4000],
    heightmapBin: "/heightmaps/kunar.bin",
    heightmapMeta: "/heightmaps/kunar.json",
    tilePattern: "/tiles/kunar/{z}/{x}/{y}.jpg",
    tileMaxZoom: 4,
  },
];

export const DEFAULT_MAP = MAPS[0];

export function findMap(key: string | null | undefined): MapConfig {
  if (!key) return DEFAULT_MAP;
  return MAPS.find((m) => m.key === key) ?? DEFAULT_MAP;
}
