// GENERATED by scripts/extract-markers.mjs — do not edit by hand.
// Re-run: `node scripts/extract-markers.mjs`
// Sources: TS Better Markers, Vanilla Reforger

export type AtlasKey = "ts" | "vanilla";

export type AtlasInfo = { url: string; width: number; height: number };

export const ATLASES: Record<AtlasKey, AtlasInfo> = {
  "ts": { url: "/icons/ts-markers.png", width: 1248, height: 1248 },
  "vanilla": { url: "/icons/vanilla-markers.png", width: 1248, height: 1520 },
};

export type IconEntry = {
  category: string;
  quad: string;
  label: string;
  atlas: AtlasKey;
  /** Sprite position within the atlas, in atlas-pixel units. */
  x: number;
  y: number;
  w: number;
  h: number;
};

export type ColorEntry = {
  name: string;
  label: string;
  hex: string;
  /** Entry name in the placed-marker config's m_aPlacedMarkerColors array
   *  (case-insensitive, e.g. "black", "white", "darkOrange").  The mod
   *  iterates GetColorEntries() and matches on this. */
  engine: string;
};

export const ICONS: IconEntry[] = [
  { category: "ts", quad: "ts-desc", label: "DESC", atlas: "ts", x: 8, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-bof", label: "SBF", atlas: "ts", x: 144, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-abf", label: "ABF", atlas: "ts", x: 280, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-aoa-right", label: "AOA RIGHT", atlas: "ts", x: 416, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-aoa-left", label: "AOA LEFT", atlas: "ts", x: 552, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-aoa-straight", label: "AOA STRAIGHT", atlas: "ts", x: 688, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-trp", label: "TRP", atlas: "ts", x: 824, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-fup", label: "FUP", atlas: "ts", x: 960, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-mep", label: "MEP", atlas: "ts", x: 1096, y: 8, w: 128, h: 128 },
  { category: "ts", quad: "ts-wp", label: "WP", atlas: "ts", x: 8, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-cp", label: "CP", atlas: "ts", x: 144, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-bp", label: "BP", atlas: "ts", x: 280, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-ip", label: "IP", atlas: "ts", x: 416, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-loip", label: "LOIP", atlas: "ts", x: 552, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-hold", label: "HOLD", atlas: "ts", x: 688, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-penetrate-right", label: "PENETRATE RIGHT", atlas: "ts", x: 824, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-penetrate-both", label: "PENETRATE BOTH", atlas: "ts", x: 960, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-passage", label: "PASSAGE", atlas: "ts", x: 1096, y: 144, w: 128, h: 128 },
  { category: "ts", quad: "ts-passage-alt", label: "PASSAGE ALT", atlas: "ts", x: 8, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-block", label: "BLOCK", atlas: "ts", x: 144, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-contain-right", label: "CONTAIN RIGHT", atlas: "ts", x: 280, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-contain-left", label: "CONTAIN LEFT", atlas: "ts", x: 416, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-contain-solid", label: "CONTAIN SOLID", atlas: "ts", x: 552, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-restrict", label: "RESTRICT", atlas: "ts", x: 688, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-delay-right", label: "DELAY RIGHT", atlas: "ts", x: 824, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-strongpoint", label: "STRONGPOINT", atlas: "ts", x: 960, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-support", label: "SUPPORT", atlas: "ts", x: 1096, y: 280, w: 128, h: 128 },
  { category: "ts", quad: "ts-screen-left", label: "SCREEN LEFT", atlas: "ts", x: 8, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-guard-left", label: "GUARD LEFT", atlas: "ts", x: 144, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-objective", label: "OBJECTIVE", atlas: "ts", x: 280, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-main-effort", label: "MAIN EFFORT", atlas: "ts", x: 416, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-aa", label: "AA", atlas: "ts", x: 552, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-aa-outline", label: "AA OUTLINE", atlas: "ts", x: 688, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-coord", label: "COORD", atlas: "ts", x: 824, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-key-terrain", label: "KEY TERRAIN", atlas: "ts", x: 960, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-row4-col9", label: "ROW4 COL9", atlas: "ts", x: 1096, y: 416, w: 128, h: 128 },
  { category: "ts", quad: "ts-row5-col1", label: "ROW5 COL1", atlas: "ts", x: 8, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-row5-col2", label: "ROW5 COL2", atlas: "ts", x: 144, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-row5-col3", label: "ROW5 COL3", atlas: "ts", x: 280, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-row5-col4", label: "ROW5 COL4", atlas: "ts", x: 416, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-flag", label: "FLAG", atlas: "ts", x: 552, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-pennant", label: "PENNANT", atlas: "ts", x: 688, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-rect-outline", label: "RECT OUTLINE", atlas: "ts", x: 824, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-return", label: "RETURN", atlas: "ts", x: 960, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-boundary-dashed", label: "BOUNDARY DASHED", atlas: "ts", x: 1096, y: 552, w: 128, h: 128 },
  { category: "ts", quad: "ts-planned-1", label: "PLANNED 1", atlas: "ts", x: 8, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-planned-2", label: "PLANNED 2", atlas: "ts", x: 144, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-planned-3", label: "PLANNED 3", atlas: "ts", x: 280, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-planned-4", label: "PLANNED 4", atlas: "ts", x: 416, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-planned-5", label: "PLANNED 5", atlas: "ts", x: 552, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-screen", label: "SCREEN", atlas: "ts", x: 688, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-bridge", label: "BRIDGE", atlas: "ts", x: 824, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-row6-col8", label: "ROW6 COL8", atlas: "ts", x: 960, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-row6-col9", label: "ROW6 COL9", atlas: "ts", x: 1096, y: 688, w: 128, h: 128 },
  { category: "ts", quad: "ts-chevron", label: "CHEVRON", atlas: "ts", x: 8, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-brace-left", label: "BRACE LEFT", atlas: "ts", x: 144, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-zigzag", label: "ZIGZAG", atlas: "ts", x: 280, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-bracket-left", label: "BRACKET LEFT", atlas: "ts", x: 416, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-bracket-right", label: "BRACKET RIGHT", atlas: "ts", x: 552, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-arrow-right", label: "ARROW RIGHT", atlas: "ts", x: 688, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-brace-right", label: "BRACE RIGHT", atlas: "ts", x: 824, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-row7-col8", label: "ROW7 COL8", atlas: "ts", x: 960, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-row7-col9", label: "ROW7 COL9", atlas: "ts", x: 1096, y: 824, w: 128, h: 128 },
  { category: "ts", quad: "ts-x-marker", label: "X MARKER", atlas: "ts", x: 8, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-rally", label: "RALLY", atlas: "ts", x: 144, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-obstacle", label: "OBSTACLE", atlas: "ts", x: 280, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-row8-col4", label: "ROW8 COL4", atlas: "ts", x: 416, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-ambush-left", label: "AMBUSH LEFT", atlas: "ts", x: 552, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-ambush-right", label: "AMBUSH RIGHT", atlas: "ts", x: 688, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-breach", label: "BREACH", atlas: "ts", x: 824, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-row8-col8", label: "ROW8 COL8", atlas: "ts", x: 960, y: 960, w: 128, h: 128 },
  { category: "ts", quad: "ts-direction", label: "DIRECTION", atlas: "ts", x: 8, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-waypoint-alt", label: "WAYPOINT ALT", atlas: "ts", x: 144, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-engineer", label: "ENGINEER", atlas: "ts", x: 280, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-transport", label: "TRANSPORT", atlas: "ts", x: 416, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-supply", label: "SUPPLY", atlas: "ts", x: 552, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-row9-col6", label: "ROW9 COL6", atlas: "ts", x: 688, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-status-1", label: "STATUS 1", atlas: "ts", x: 824, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-status-2", label: "STATUS 2", atlas: "ts", x: 960, y: 1096, w: 128, h: 128 },
  { category: "ts", quad: "ts-status-3", label: "STATUS 3", atlas: "ts", x: 1096, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "circle", label: "CIRCLE", atlas: "vanilla", x: 552, y: 280, w: 128, h: 128 },
  { category: "general", quad: "circle-2", label: "CIRCLE 2", atlas: "vanilla", x: 688, y: 280, w: 128, h: 128 },
  { category: "general", quad: "cross", label: "CROSS", atlas: "vanilla", x: 8, y: 416, w: 128, h: 128 },
  { category: "general", quad: "cross-2", label: "CROSS 2", atlas: "vanilla", x: 144, y: 416, w: 128, h: 128 },
  { category: "general", quad: "dot", label: "DOT", atlas: "vanilla", x: 144, y: 552, w: 128, h: 128 },
  { category: "general", quad: "dot-2", label: "DOT 2", atlas: "vanilla", x: 280, y: 552, w: 128, h: 128 },
  { category: "general", quad: "drop-point", label: "DROP POINT", atlas: "vanilla", x: 416, y: 552, w: 128, h: 128 },
  { category: "general", quad: "drop-point-2", label: "DROP POINT 2", atlas: "vanilla", x: 552, y: 552, w: 128, h: 128 },
  { category: "general", quad: "entry-point", label: "ENTRY POINT", atlas: "vanilla", x: 688, y: 552, w: 128, h: 128 },
  { category: "general", quad: "entry-point-2", label: "ENTRY POINT 2", atlas: "vanilla", x: 824, y: 552, w: 128, h: 128 },
  { category: "general", quad: "flag", label: "FLAG", atlas: "vanilla", x: 960, y: 552, w: 128, h: 128 },
  { category: "general", quad: "flag-2", label: "FLAG 2", atlas: "vanilla", x: 1096, y: 552, w: 128, h: 128 },
  { category: "general", quad: "flag-3", label: "FLAG 3", atlas: "vanilla", x: 8, y: 688, w: 128, h: 128 },
  { category: "general", quad: "fortification", label: "FORTIFICATION", atlas: "vanilla", x: 416, y: 688, w: 128, h: 128 },
  { category: "general", quad: "fortification-2", label: "FORTIFICATION 2", atlas: "vanilla", x: 552, y: 688, w: 128, h: 128 },
  { category: "general", quad: "mark-exclamation", label: "MARK EXCLAMATION", atlas: "vanilla", x: 280, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mark-exclamation-2", label: "MARK EXCLAMATION 2", atlas: "vanilla", x: 416, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mark-exclamation-3", label: "MARK EXCLAMATION 3", atlas: "vanilla", x: 552, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mark-question", label: "MARK QUESTION", atlas: "vanilla", x: 688, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mark-question-2", label: "MARK QUESTION 2", atlas: "vanilla", x: 824, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mark-question-3", label: "MARK QUESTION 3", atlas: "vanilla", x: 960, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mine-field", label: "MINE FIELD", atlas: "vanilla", x: 1096, y: 824, w: 128, h: 128 },
  { category: "general", quad: "mine-field-2", label: "MINE FIELD 2", atlas: "vanilla", x: 8, y: 960, w: 128, h: 128 },
  { category: "general", quad: "mine-field-3", label: "MINE FIELD 3", atlas: "vanilla", x: 144, y: 960, w: 128, h: 128 },
  { category: "general", quad: "mine-single", label: "MINE SINGLE", atlas: "vanilla", x: 280, y: 960, w: 128, h: 128 },
  { category: "general", quad: "mine-single-2", label: "MINE SINGLE 2", atlas: "vanilla", x: 416, y: 960, w: 128, h: 128 },
  { category: "general", quad: "mine-single-3", label: "MINE SINGLE 3", atlas: "vanilla", x: 552, y: 960, w: 128, h: 128 },
  { category: "general", quad: "objective-marker", label: "OBJECTIVE MARKER", atlas: "vanilla", x: 688, y: 960, w: 128, h: 128 },
  { category: "general", quad: "objective-marker-2", label: "OBJECTIVE MARKER 2", atlas: "vanilla", x: 824, y: 960, w: 128, h: 128 },
  { category: "general", quad: "observation-post", label: "OBSERVATION POST", atlas: "vanilla", x: 960, y: 960, w: 128, h: 128 },
  { category: "general", quad: "observation-post-2", label: "OBSERVATION POST 2", atlas: "vanilla", x: 1096, y: 960, w: 128, h: 128 },
  { category: "general", quad: "pick-up", label: "PICK UP", atlas: "vanilla", x: 8, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "pick-up-2", label: "PICK UP 2", atlas: "vanilla", x: 144, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "point-of-interest", label: "POINT OF INTEREST", atlas: "vanilla", x: 280, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "point-of-interest-2", label: "POINT OF INTEREST 2", atlas: "vanilla", x: 416, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "point-of-interest-3", label: "POINT OF INTEREST 3", atlas: "vanilla", x: 552, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "point-special", label: "POINT SPECIAL", atlas: "vanilla", x: 688, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "point-special-2", label: "POINT SPECIAL 2", atlas: "vanilla", x: 824, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "recon-outpost", label: "RECON OUTPOST", atlas: "vanilla", x: 960, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "recon-outpost-2", label: "RECON OUTPOST 2", atlas: "vanilla", x: 1096, y: 1096, w: 128, h: 128 },
  { category: "general", quad: "waypoint", label: "WAYPOINT", atlas: "vanilla", x: 1096, y: 1232, w: 128, h: 128 },
  { category: "general", quad: "waypoint-2", label: "WAYPOINT 2", atlas: "vanilla", x: 8, y: 1368, w: 128, h: 128 },
  { category: "tactical", quad: "defend", label: "DEFEND", atlas: "vanilla", x: 280, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "defend-2", label: "DEFEND 2", atlas: "vanilla", x: 416, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "destroy", label: "DESTROY", atlas: "vanilla", x: 552, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "destroy-2", label: "DESTROY 2", atlas: "vanilla", x: 688, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "heal", label: "HEAL", atlas: "vanilla", x: 688, y: 688, w: 128, h: 128 },
  { category: "tactical", quad: "help", label: "HELP", atlas: "vanilla", x: 824, y: 688, w: 128, h: 128 },
  { category: "tactical", quad: "help-2", label: "HELP 2", atlas: "vanilla", x: 960, y: 688, w: 128, h: 128 },
  { category: "tactical", quad: "attack", label: "ATTACK", atlas: "vanilla", x: 280, y: 280, w: 128, h: 128 },
  { category: "tactical", quad: "attack-main", label: "ATTACK MAIN", atlas: "vanilla", x: 416, y: 280, w: 128, h: 128 },
  { category: "tactical", quad: "contain", label: "CONTAIN", atlas: "vanilla", x: 824, y: 280, w: 128, h: 128 },
  { category: "tactical", quad: "contain-2", label: "CONTAIN 2", atlas: "vanilla", x: 960, y: 280, w: 128, h: 128 },
  { category: "tactical", quad: "contain-3", label: "CONTAIN 3", atlas: "vanilla", x: 1096, y: 280, w: 128, h: 128 },
  { category: "tactical", quad: "retain", label: "RETAIN", atlas: "vanilla", x: 144, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "retain-2", label: "RETAIN 2", atlas: "vanilla", x: 280, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "strong-point", label: "STRONG POINT", atlas: "vanilla", x: 552, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "strong-point-2", label: "STRONG POINT 2", atlas: "vanilla", x: 688, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "target-reference-point", label: "TARGET REFERENCE POINT", atlas: "vanilla", x: 824, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "target-reference-point-2", label: "TARGET REFERENCE POINT 2", atlas: "vanilla", x: 960, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "ambush", label: "AMBUSH", atlas: "vanilla", x: 8, y: 8, w: 128, h: 128 },
  { category: "tactical", quad: "ambush-2", label: "AMBUSH 2", atlas: "vanilla", x: 144, y: 8, w: 128, h: 128 },
  { category: "tactical", quad: "reconnaissance", label: "RECONNAISSANCE", atlas: "vanilla", x: 8, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "search-area", label: "SEARCH AREA", atlas: "vanilla", x: 416, y: 1232, w: 128, h: 128 },
  { category: "tactical", quad: "direction-of-attack", label: "DIRECTION OF ATTACK", atlas: "vanilla", x: 824, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "direction-of-attack-main", label: "DIRECTION OF ATTACK MAIN", atlas: "vanilla", x: 960, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "direction-of-attack-main-planned", label: "DIRECTION OF ATTACK MAIN PLANNED", atlas: "vanilla", x: 1096, y: 416, w: 128, h: 128 },
  { category: "tactical", quad: "direction-of-attack-planned", label: "DIRECTION OF ATTACK PLANNED", atlas: "vanilla", x: 8, y: 552, w: 128, h: 128 },
  { category: "tactical", quad: "follow-and-support", label: "FOLLOW AND SUPPORT", atlas: "vanilla", x: 144, y: 688, w: 128, h: 128 },
  { category: "tactical", quad: "follow-and-support-2", label: "FOLLOW AND SUPPORT 2", atlas: "vanilla", x: 280, y: 688, w: 128, h: 128 },
  { category: "tactical", quad: "join", label: "JOIN", atlas: "vanilla", x: 1096, y: 688, w: 128, h: 128 },
  { category: "tactical", quad: "join-2", label: "JOIN 2", atlas: "vanilla", x: 8, y: 824, w: 128, h: 128 },
  { category: "tactical", quad: "join-3", label: "JOIN 3", atlas: "vanilla", x: 144, y: 824, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-large", label: "ARROW LARGE", atlas: "vanilla", x: 280, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-large-2", label: "ARROW LARGE 2", atlas: "vanilla", x: 416, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-large-3", label: "ARROW LARGE 3", atlas: "vanilla", x: 552, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-medium", label: "ARROW MEDIUM", atlas: "vanilla", x: 688, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-medium-2", label: "ARROW MEDIUM 2", atlas: "vanilla", x: 824, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-medium-3", label: "ARROW MEDIUM 3", atlas: "vanilla", x: 960, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-small", label: "ARROW SMALL", atlas: "vanilla", x: 1096, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-small-2", label: "ARROW SMALL 2", atlas: "vanilla", x: 8, y: 280, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-small-3", label: "ARROW SMALL 3", atlas: "vanilla", x: 144, y: 280, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-large", label: "ARROW CURVE LARGE", atlas: "vanilla", x: 280, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-large-2", label: "ARROW CURVE LARGE 2", atlas: "vanilla", x: 416, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-large-3", label: "ARROW CURVE LARGE 3", atlas: "vanilla", x: 552, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-medium", label: "ARROW CURVE MEDIUM", atlas: "vanilla", x: 688, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-medium-2", label: "ARROW CURVE MEDIUM 2", atlas: "vanilla", x: 824, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-medium-3", label: "ARROW CURVE MEDIUM 3", atlas: "vanilla", x: 960, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-small", label: "ARROW CURVE SMALL", atlas: "vanilla", x: 1096, y: 8, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-small-2", label: "ARROW CURVE SMALL 2", atlas: "vanilla", x: 8, y: 144, w: 128, h: 128 },
  { category: "arrow", quad: "arrow-curve-small-3", label: "ARROW CURVE SMALL 3", atlas: "vanilla", x: 144, y: 144, w: 128, h: 128 },
];

// Palette matches the engine's placed-marker color config 1:1, plus `black`
// added by the TS Better Markers dependency.  `engine` is the config name the
// mod resolves via GetColorEntries().  `hex` is the sRGB value that displays
// identically to what the engine renders in-game (the engine's own config
// stores these in *linear* RGB — don't paste those floats as hex here, they
// look way darker in a browser).  Figma node 19:1159 has the source-of-truth
// sRGB hex values.
export const COLORS: ColorEntry[] = [
  { name: "BLACK",       label: "Black",        hex: "#000000", engine: "black" },
  { name: "DARK_BROWN",  label: "Dark Brown",   hex: "#60383d", engine: "darkBrown" },
  { name: "PURPLE",      label: "Purple",       hex: "#9151a0", engine: "purple" },
  { name: "PING",        label: "Ping",         hex: "#f038db", engine: "ping" },
  { name: "NAVY_BLUE",   label: "Navy Blue",    hex: "#0d6079", engine: "navyBlue" },
  { name: "CYAN",        label: "Cyan",         hex: "#22c3f3", engine: "cyan" },
  { name: "BLUE",        label: "Blue",         hex: "#0d7aed", engine: "blue" },
  { name: "DARK_GREEN",  label: "Dark Green",   hex: "#005b26", engine: "darkGreen" },
  { name: "GREEN",       label: "Green",        hex: "#22b24f", engine: "green" },
  { name: "RED",         label: "Red",          hex: "#ee2e2e", engine: "red" },
  { name: "DARK_RED",    label: "Dark Red",     hex: "#821c1c", engine: "darkRed" },
  { name: "DARK_ORANGE", label: "Dark Orange",  hex: "#e2a84f", engine: "darkOrange" },
  { name: "ORANGE",      label: "Orange",       hex: "#f9d368", engine: "orange" },
  { name: "WHITE",       label: "White",        hex: "#ffffff", engine: "white" },
];

export const DEFAULT_ICON = ICONS[0];
export const DEFAULT_COLOR = COLORS.find(c => c.name === "BLACK") ?? COLORS[0];
